export const metadata = {
  title: 'My Test Webpage',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <nav>
          <h1>Navbar</h1>

          <ul>
            <li>Home</li>
            <li>Bottom</li>
          </ul>
        </nav>
        
        {children}
      </body>
    </html>
  )
}
